[package]
name = "cuda-driver-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen.workspace = true

[features]
default = ["static"]
# Static linking against cuda libraries
static = []
