[workspace]
members = [
    "crates/nv_video_codec_sdk",
    "crates/video-common",
    "crates/nvptx-panic-handler",
    "crates/ssimulacra2-cuda-kernel",
    "crates/ssimulacra2-cuda",
    "crates/cuda_npp_sys",
    "crates/cuda_npp"
]
resolver = "2"

[package]
name = "video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
video-common = { version = "0.1", path = "crates/video-common" }
nv_video_codec_sdk = { version = "0.1", path = "crates/nv_video_codec_sdk" }
matroska-demuxer = "0.5"
bitstream-io = "2"
