[workspace]
members = [
    "crates/cuda-driver",
    "crates/cuda_npp",
    "crates/cuda_npp_sys",
    "crates/nv_video_codec_sdk",
    "crates/nvptx-core",
    "crates/ssimulacra2-cuda-kernel",
    "crates/ssimulacra2-cuda",
    "crates/video-common",
]
resolver = "2"

[profile.release-nvptx]
inherits = "release"
opt-level = 3
lto = "fat"
debug = "full"
codegen-units = 1
overflow-checks = false

[workspace.dependencies]
array-init = "2"
bindgen = "0.69"
cudarc = { version = "0.10", default-features = false, features = ["std", "driver"] }#, "cuda-version-from-build-system", "dynamic-linking"] }
paste = "1"
rerun = "0.16"
zune-image = { version = "0.4", default-features = false, features = ["png", "simd", "metadata"] }
nalgebra = "0.32"

[package]
name = "video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
video-common = { version = "0.1", path = "crates/video-common" }
nv_video_codec_sdk = { version = "0.1", path = "crates/nv_video_codec_sdk" }
matroska-demuxer = "0.5"
bitstream-io = "2"
