[package]
name = "vmaf-cuda"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
cuda-driver = { workspace = true }
cuda-npp = { workspace = true, features = ["isu", "ial", "ist"] }
zune-image.workspace = true
