[package]
name = "vmaf-cuda-kernel"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license = "MIT"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
nvptx-core = { workspace = true }
