[package]
name = "vmaf-cuda-kernel"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
nvptx-core = { workspace = true }
