[package]
name = "ssimulacra2-cuda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init.workspace = true
cudarc.workspace = true
cuda_npp = { version = "0.1", path = "../cuda_npp" }
video-common = { version = "0.1", path = "../video-common" }
zune-image.workspace = true
