[package]
name = "ssimulacra2-cuda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = { workspace = true }
cuda-driver = { version = "0.1", path = "../cuda-driver" }
cuda-npp = { version = "0.1", path = "../cuda-npp", features = ["isu", "ial", "idei", "if", "ist"] }
indices = { workspace = true }
zune-image.workspace = true

[build-dependencies]
nalgebra = "0.32"
