[package]
name = "vmaf"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version = "1.77"

[dependencies]

[build-dependencies]
bindgen = { workspace = true }

[features]
default = []
builtin_models = []
