[package]
name = "amf-sys"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
widestring = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
