[package]
name = "amf"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version = "1.77"

[dependencies]
amf-sys = { workspace = true }
libloading = { workspace = true }
widestring = { workspace = true }
