[package]
name = "quick-stats"
version = "0.1.0"
description = "Quick stats"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license = "MIT"

[dependencies]
